### ISSUE TITLE
Both Helm 2 & 3 are not working for local dev and/or the documentation is outdated

### ISSUE THREAD

**Issue by at15** [pingcap/chaos-mesh#352] opened 2020-03-20 23:00 UTC
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-05-17T01:27:29Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Following [deploying chaos-mesh to local kind cluster](https://yisaer.gitbook.io/chaos-mesh-contributing-tutorials/da-jian-chaosmesh-ben-di-kai-fa-huan-jing/ben-di-bian-yi-yun-hang-chaosmesh#bu-shu-chaosmesh-dao-ben-di-ji-qun) in chaos mesh contributor guide

The command I used for helm3 is `helm install chaos . --namespace chaos-testing --set controllerManager.image="localhost:5000/pingcap/chaos-mesh:latest" --set controllerManager.imagePullPolicy="IfNotPresent"`

**What did you expect to see?**

Helm install success

**What did you see instead?**

Helm3

This seems to be a well know issue https://github.com/jetstack/cert-manager/issues/1702, https://github.com/jetstack/cert-manager/issues/1143 https://github.com/helm/helm/issues/6883

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[0].clientConfig): missing required field "caBundle" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig
```

I do see `caBundle` in https://github.com/pingcap/chaos-mesh/blob/master/helm/chaos-mesh/templates/webhook-configuration.yaml#L71

Helm2

```
Error: release chaos failed: namespaces "chaos-testing" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "chaos-testing"
```

I guess I need to update the role binding for `chaos-testing` namespace, but I am wondering if there is anyplace I can copy and paste from (伸手党.jpg)

**Comment by cwen0** [comment] 2020-03-21 03:45
@at15 Can you share the helm version?  I can't reproduce this issue in my environment with helm v3.1.0.  

About helm 2, you can apply this file [tiller-rbac.yaml](https://github.com/pingcap/chaos-mesh/blob/master/manifests/tiller-rbac.yaml) and init helm with `--service-account=tiller` field. 

```
kubectl apply -f manifests/tiller-rbac.yaml 
helm init --service-account=tiller
```

**Comment by cwen0** [comment] 2020-03-21 04:22
@at15 I have reproduced this issue with helm v3.1.0 and I am working on it.

**Comment by cwen0** [comment] 2020-03-21 04:43
@at15 you can use `./hack/kind-cluster-build.sh -k v1.17.2`  to skip this issue temporarily when you use helm 3.  this command will install v1.17.2 Kubernetes.

**Comment by at15** [comment] 2020-03-21 05:12
Thanks! @cwen0 changed the server version to 1.17.2 worked

```
```bash
./hack/kind-cluster-build.sh -n chaos-mesh -c 3 -k v1.17.2
helm install chaos helm/chaos-mesh --namespace chaos-testing --set controllerManager.image="localhost:5000/pingcap/chaos-mesh:latest" --set controllerManager.imagePullPolicy="IfNotPresent"
```

**Comment by cwen0** [comment] 2020-03-21 05:46
@at15 This issue is fixed in #354 ,  `caBundle` was marked as a required field in v1.12.8 Kubernetes. And we add Validator recently.

**Closed** 2020-03-21 10:03 UTC
