### ISSUE TITLE
why doesn't the example "web-show" work as expected?

### ISSUE THREAD

**Issue by AndyXia23** [pingcap/chaos-mesh#319] opened 2020-03-07 16:04 UTC
**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"$Format:%H$", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
Run the example `web-show` 
(1)` ./deploy.sh --docker-mirror` 
(2) `kubectl apply -f network-delay.yaml`

**What did you expect to see?**
The effect of the experiment is expected to be shown on the front-end.

**What did you see instead?**
After I ran the command `kubectl apply -f network-delay.yaml`, the image was the same as before. I was afraid that the experiment wasn't carried out. I guessed that the phase of experiment was failed after I ran the command `kubectl describe networkchaos`  and the output was as follow:
```
Name:         network-delay-example
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"pingcap.com/v1alpha1","kind":"NetworkChaos","metadata":{"annotations":{},"name":"network-delay-example","namespace":"defaul...
API Version:  pingcap.com/v1alpha1
Kind:         NetworkChaos
Metadata:
  Creation Timestamp:  2020-03-07T02:48:04Z
  Finalizers:
    default/web-show-5b97769b4f-sq5jp
  Generation:        9
  Resource Version:  5216543
  Self Link:         /apis/pingcap.com/v1alpha1/namespaces/default/networkchaos/network-delay-example
  UID:               1136e7c1-601e-11ea-975c-b4969167e3cc
Spec:
  Action:  delay
  Delay:
    Correlation:  100
    Duration:     30s
    Jitter:       0ms
    Latency:      10ms
  Direction:      
  Mode:           one
  Scheduler:
    Cron:  @every 60s
  Selector:
    Label Selectors:
      App:  web-show
    Namespaces:
      default
  Target:
    Mode:  
    Selector:
    Value:  
  Value:    
Status:
  Experiment:
    Phase:  Failed
  Phase:    
Events:     <none>
```

**Comment by cwen0** [comment] 2020-03-07 16:09
@AndyXia23 Can you check the status of all chaos mesh pods?
```
kubectl get pod -n chaos-testing
```

**Comment by AndyXia23** [comment] 2020-03-07 16:14
@cwen0 
$ kubectl get pod -n chaos-testing
No resources found.

**Comment by cwen0** [comment] 2020-03-07 16:23
@AndyXia23 From the message, you can't install Chaos Mesh! You can refer this document to install Chaos Mesh [get started on kind](https://github.com/pingcap/chaos-mesh/blob/master/doc/get_started_on_kind.md) 

If you can't access to docker.io, you can try `./install.sh --local kind --docker-mirror` to install chaos mesh

**Comment by AndyXia23** [comment] 2020-03-08 05:19
@cwen0 I tried `./install.sh --local kind --docker-mirror`, but why some pods are pending?
```
$ kubectl get pods --namespace chaos-testing -l app.kubernetes.io/instance=chaos-mesh
NAME                                        READY   STATUS    RESTARTS   AGE
bpfki-clvck                                 0/2     Pending   0          87m
bpfki-dmc9t                                 2/2     Running   0          87m
bpfki-k6vdl                                 0/2     Pending   0          87m
chaos-controller-manager-66f565d45f-vqq94   1/1     Running   0          87m
chaos-daemon-drb7c                          1/1     Running   0          87m
chaos-daemon-lf7h5                          1/1     Running   0          87m
chaos-daemon-zttkd                          0/1     Pending   0          87m
```

**Comment by AndyXia23** [comment] 2020-03-08 05:52
@cwen0 After I ran` ./deploy.sh --docker-mirror`, another issue was as follow:
```
~/chaos-mesh/examples/web-show$ kubectl apply -f network-delay.yaml 
Error from server: error when creating "network-delay.yaml": admission webhook "admission-webhook.pingcap.com" denied the request: invalid configuration
```

**Comment by cwen0** [comment] 2020-03-08 07:24
> @cwen0 I tried ./install.sh --local kind --docker-mirror, but why some pods are pending?

@AndyXia23 Can you update the Chaos mesh repo?  `bpfki` is an alpha future, we disable it at this pr https://github.com/pingcap/chaos-mesh/pull/318.

**Comment by AndyXia23** [comment] 2020-03-08 08:47
@cwen0 I updated it and it worked. And then I want to use the example `web-show` to start a chaos experiment. But after I ran `kubectl apply -f network-delay.yaml`, the image on the front end did not change and it was still like this:
![图片](https://user-images.githubusercontent.com/59043762/76159428-525d8400-615b-11ea-8c3c-0c3919af0812.png)

**Comment by cwen0** [comment] 2020-03-08 08:49
@AndyXia23 Can you give me the whole log of chaos-manager and check test status of all chaos pods?

**Comment by AndyXia23** [comment] 2020-03-08 08:54
@cwen0 
```
~/chaos-mesh/examples/web-show$ kubectl get pods -n chaos-testing
NAME                                        READY   STATUS    RESTARTS   AGE
chaos-controller-manager-66f565d45f-lww8r   1/1     Running   0          22m
chaos-daemon-8lgfr                          1/1     Running   0          22m
chaos-daemon-wktrf                          1/1     Running   0          22m
chaos-daemon-x6scb                          1/1     Running   0          22m
```

And where can I get the log of chaos-manager?

**Comment by cwen0** [comment] 2020-03-08 08:56
@AndyXia23 

this comment can helm you: 

```
kubectl get pod --namespace=chaos-testing | grep controller | awk '{print $1}' | xargs -I {} kubectl logs {} -n chaos-testing
```

**Comment by AndyXia23** [comment] 2020-03-08 09:02
@cwen0 
![图片](https://user-images.githubusercontent.com/59043762/76159690-ff390080-615d-11ea-9d97-bbf7df766c8f.png)

**Comment by AndyXia23** [comment] 2020-03-08 09:06
@cwen0 Actually I deleted podchaos before. 
```
~/chaos-mesh$ kubectl get podchaos.pingcap.com --all-namespaces
No resources found
```

**Comment by cwen0** [comment] 2020-03-08 09:06
@AndyXia23 Can you give me the whole log file?

**Comment by cwen0** [comment] 2020-03-08 09:09
@AndyXia23 Can you join our slack channel or give me the other contact info for I can help you debug this issue?

**Comment by AndyXia23** [comment] 2020-03-08 09:22
@cwen0 The log file was too long to write here so I sent you a email.

**Comment by cwen0** [comment] 2020-03-08 10:23
@AndyXia23 Thanks for your email, I have received your log. Can you run the following comments to get some logs?  

```
kubectl get pod --namespace chaos-testing -o wide | grep kind-worker2 | grep chaos-daemo | awk '{print $1}' | xargs -I {} kubectl logs {} -n chaos-testing 
kubectl get pod | grep web-show | awk '{print $1}' | xargs -I {} kubectl logs {}
```

**Comment by AndyXia23** [comment] 2020-03-08 10:58
@cwen0 I sent two logs to your email.

**Comment by cwen0** [comment] 2020-03-09 03:58
@AndyXia23 This issue caused by the repeated Kubernetes cluster, I will close this issue.

**Closed** 2020-03-09 03:58 UTC
