### ISSUE TITLE
latest chaos-mesh (master) not work on k3s

### ISSUE THREAD

**Issue by moonspirit** [pingcap/chaos-mesh#344] opened 2020-03-16 13:34 UTC
Three weeks ago, it ok to use chao-mesh in my local k3s environment. when i reinstall k3s today and found that chaos-mesh is unable to create podchaos using latest image and crds.

Error from server (InternalError): error when creating "pod-kill-example.yaml": Internal error occurred: failed calling webhook "mpodchaos.kb.io": Post https://chaos-mesh-controller-manager.chaos-testing.svc:443/mutate-pingcap-com-v1alpha1-podchaos?timeout=30s: x509: certificate signed by unknown authority

**Comment by zhouqiang-cl** [comment] 2020-03-17 07:05
@cwen0 is working on this

**Comment by cwen0** [comment] 2020-03-17 11:37
@moonspirit you can try `cert-manager` for certificate management to solve this issue, refer this document: https://github.com/pingcap/chaos-mesh/tree/master/helm/chaos-mesh#configuration-and-installation-details

**Comment by huangwei2013** [comment] 2020-04-10 09:38
Met the same problem， and try as [cwen0 provided](https://github.com/pingcap/chaos-mesh/tree/master/helm/chaos-mesh#configuration-and-installation-details) but nothing changed.

**Comment by cwen0** [comment] 2020-04-10 10:10
@huangwei2013  Did you also run Chaos Mesh in k3s environment? In addition, Can you check the certs in the `/etc/webhook/certs/ directory of `chaos-controller-manager` pod and running the following commands to get more information? 

```
kubectl version 
kubectl get MutatingWebhookConfiguration chaos-mesh-sidecar-injector -o yaml 
```

**Comment by huangwei2013** [comment] 2020-04-13 03:15
@cwen0 
I running on minikube(v1.7.3), all-in-one model by a AliCloud Server



> [root@dev-1 ~]# kubectl version 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}



> [root@dev-1 ~]# kubectl get MutatingWebhookConfiguration chaos-mesh-sidecar-injector -o yaml 
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: "2020-04-10T03:33:59Z"
  generation: 1
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chaos-mesh
    helm.sh/chart: chaos-mesh-dev
  name: chaos-mesh-sidecar-injector
  resourceVersion: "7424541"
  selfLink: /apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/chaos-mesh-sidecar-injector
  uid: b1f8942d-823f-467d-9ac7-23c4ebca7ded
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /inject-v1-pod
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  name: admission-webhook.pingcap.com
  namespaceSelector:
    matchLabels:
      admission-webhook: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /mutate-pingcap-com-v1alpha1-podchaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mpodchaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podchaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /mutate-pingcap-com-v1alpha1-iochaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: miochaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - iochaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /mutate-pingcap-com-v1alpha1-timechaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mtimechaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timechaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /mutate-pingcap-com-v1alpha1-networkchaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mnetworkchaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkchaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /mutate-pingcap-com-v1alpha1-kernelchaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mkernelchaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kernelchaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30

**Comment by cwen0** [comment] 2020-04-13 03:32
@huangwei2013 Hi, judging from the information you provided, I guess that you did not enable `cert-manager`.  If you have deployed `cert-manager` in your cluster, you can set the `webhook. certManager.enabeled` to true in [value.yaml](https://github.com/pingcap/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml#L162) and upgrade Chaos Mesh.  In addition, If you don't want to use `cert-manager`, you can update your helm files and upgrade the Chaos Mesh, your issue may be fixed in this pr #369

**Comment by huangwei2013** [comment] 2020-04-13 04:42
I have installed cert-manager as [doc](https://github.com/pingcap/chaos-mesh/tree/master/helm/chaos-mesh#configuration-and-installation-details)
and set  `webhook. certManager.enabeled`， by uninstall and re-install . but...

**Comment by Gallardot** [comment] 2020-04-14 02:01
@huangwei2013 

Could you follow this step? It looks like a similar problem. 

https://github.com/pingcap/chaos-mesh/issues/400#issuecomment-610734578

**Comment by huangwei2013** [comment] 2020-04-16 10:08
@Gallardot thx for help. I have done

**Comment by yeya24** [comment] 2020-04-30 16:35
@moonspirit Hi, do you mind updating us on the status? Is this issue fixed or still reproducible? If not, I think we can close it.

**Comment by cwen0** [comment] 2020-05-07 13:06
I think we can close it.

**Closed by cwen0** 2020-05-07 13:06 UTC
Labels: type/bug

**Comment by rajdhandus** [comment] 2022-05-18 21:30
this happened to us and we had to delete the validatingwebhookconfiguration for chaos-mesh as mentioned in the below comment for a related issue and it worked!!

https://github.com/kubernetes/ingress-nginx/issues/5401#issuecomment-662424306
