### ISSUE TITLE
secrets "chaos-mesh-webhook-certs" not found when creating chaos-controller-manager

### ISSUE THREAD

**Issue by wwjgit** [pingcap/chaos-mesh#400] opened 2020-04-03 15:04 UTC
## Bug Report

**What version of Kubernetes are you using?**

v1.12.10
**What did you do?**

cd chaos-mesh
kubectl apply -f manifests/
helm install helm/chaos-mesh --name=chaos-mesh --namespace=chaos-testing
kubectl get pods --namespace chaos-testing -l app.kubernetes.io/instance=chaos-mesh

**What did you expect to see?**
chaos-controller-manager should be running
       
**What did you see instead?**
kubectl describe the chaos-contoller manager, I got below error message
Events:
  Warning  FailedMount  100s (x8 over 2m44s)  kubelet, 10-196-108-37  MountVolume.SetUp failed for volume "webhook-certs" : secrets "chaos-mesh-webhook-certs" not found

**Comment by Gallardot** [comment] 2020-04-04 05:29
It is possible that the image is still being downloaded due to a network exception.Maybe you can try it again.

I think we can optimize the process. @cwen0

**Comment by wwjgit** [comment] 2020-04-05 08:58
@Gallardot may I ask which image? I tried it several times and got the same warning message.

**Comment by shiju-tech** [comment] 2020-04-05 13:25
i am too facing the same issue with chaos-controller-manager , error is "SetUp failed for volume "webhook-certs" : secret "chaos-mesh-webhook-certs" not found"

also 
chaos-daemons fails with mesage "Failed to pull image "pingcap/chaos-daemon:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io"

**Comment by cwen0** [comment] 2020-04-05 16:11
@wwjgit 
Sorry for the late response. `bitnami/kubectl:latest` will be used when installing Chaos Mesh, Chaos mesh use this image to create the certificate for webhook. So the controller-manager must wait for certificates to start before it can run normally. You also can use cert-manager for certificate management, here is the related document: https://github.com/pingcap/chaos-mesh/tree/master/helm/chaos-mesh#using-cert-manager-for-certificate-management

@Gallardot Maybe we can create a certificate in the `controller-manager` program at the beginning.  Do you have any good ideas about this optimization?

**Comment by cwen0** [comment] 2020-04-05 16:14
> i am too facing the same issue with chaos-controller-manager , error is "SetUp failed for volume "webhook-certs" : secret "chaos-mesh-webhook-certs" not found"
> 
> also
> chaos-daemons fails with mesage "Failed to pull image "pingcap/chaos-daemon:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io"

Can you make sure that each Kubernetes node has the access to `docker.io`?

**Comment by Gallardot** [comment] 2020-04-06 14:15
> @Gallardot Maybe we can create a certificate in the `controller-manager` program at the beginning. Do you have any good ideas about this optimization?

@cwen0 
Earlier versions of controller-rumtime implemented the logic you mentioned. They abandoned the implementation because of cert-manager. I have a suggestion to use pre-install of helm hook. I'll try that later.

**Comment by Gallardot** [comment] 2020-04-06 14:20
@wwjgit @shiju-tech 

Could you give me more information please？
```
kubectl version
kubectl get csr chaos-mesh-controller-manager.chaos-testing -o yaml
kubectl get secret chaos-mesh-webhook-certs -n chaos-testing -o yaml
```

**Comment by shiju-tech** [comment] 2020-04-06 15:47
@Gallardot @wwjgit  Thanks for your response.

@Gallardot  please see the info you asked for 

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCom                                                                                                             mit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:                                                                                                             "2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd                                                                                                             64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCom                                                                                                             mit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:                                                                                                             "2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd                                                                                                             64"}


kubectl get csr chaos-mesh-controller-manager.chaos-testing -o yaml

Error from server (NotFound): certificatesigningrequests.certificates.k8s.io "chaos-mesh-controller-manager.chaos-testing" not found

kubectl get secret chaos-mesh-webhook-certs -n chaos-testing -o yaml

Error from server (NotFound): secrets "chaos-mesh-webhook-certs" not found

Let me know if you need more details

**Comment by wwjgit** [comment] 2020-04-07 01:47
kubectl version  
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:50:59Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-45+c49c6cc7ec3af7", GitCommit:"c49c6cc7ec3af777e580543db675b2d54533afaf", GitTreeState:"clean", BuildDate:"2019-03-20T07:45:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

kubectl get csr chaos-mesh-controller-manager.chaos-testing -o yaml    
Error from server (NotFound): certificatesigningrequests.certificates.k8s.io "chaos-mesh-controller-manager.chaos-testing" not found

kubectl get secret chaos-mesh-webhook-certs -n chaos-testing -o yaml    
Error from server (NotFound): secrets "chaos-mesh-webhook-certs" not found

**Comment by wwjgit** [comment] 2020-04-07 09:42
@cwen0 I pulled the image bitnami/kubectl:latest manually and still got the same warning message.

**Comment by cwen0** [comment] 2020-04-07 10:02
@wwjgit Did you pull `bitnami/kubectl:latest` image on the Node that the webhook job run on it? 
In addition, what is the final state of `chaos-controller-manager`? Is it always in `Creating`? If so, you can use the `kubectl describe` command to describe the webhook job and get more information.

**Comment by cwen0** [comment] 2020-04-07 10:14
@wwjgit About the warning message, @

**Comment by wwjgit** [comment] 2020-04-07 13:37
> Did you pull `bitnami/kubectl:latest` image on the Node that the webhook job run on it?

yes. I only have one node in the cluster. I pulled the image on that node.

> In addition, what is the final state of `chaos-controller-manager`? Is it always in `Creating`?

yes. It is 'ContainerCreating'.

>  If so, you can use the `kubectl describe` command to describe the webhook job and get more information.

sorry, describe which webhook job?

**Comment by cwen0** [comment] 2020-04-07 15:54
@wwjgit Can you run the following commands to get more information? 

```
kubectl get pod -n chaos-testing -o wide
kubectl get secrets -n chaos-testing
``` 

If you found some pods with `webhook` prefix, can you use `kubectl describe pod webhook-xxx -n chaos-testing` to check the pod status?

**Comment by wwjgit** [comment] 2020-04-08 01:53
kubectl get pod -n chaos-testing -o wide    
NAME                                        READY   STATUS              RESTARTS   AGE   IP            NODE       NOMINATED NODE   READINESS GATES
chaos-collector-database-5f56c7f66-wd2rb    1/1     Running             0          16h   172.17.0.13   minikube   <none>           <none>
chaos-controller-manager-7bc9664c9b-qjjp2   0/1     ContainerCreating   0          17h   <none>        minikube   <none>           <none>
chaos-daemon-dgxxv                          1/1     Running             0          17h   172.17.0.10   minikube   <none>           <none>
chaos-dashboard-67f68b5764-x2pxs            1/1     Running             0          16h   172.17.0.15   minikube   <none>           <none>

kubectl get secrets -n chaos-testing
NAME                                   TYPE                                  DATA   AGE
chaos-controller-manager-token-9jlwl   kubernetes.io/service-account-token   3      17h
chaos-dashboard-token-44wmg            kubernetes.io/service-account-token   3      16h
default-token-hhgrw                    kubernetes.io/service-account-token   3      2d

@cwen0 
I can't see any pods with webhook prefix.

**Comment by Gallardot** [comment] 2020-04-08 02:22
@wwjgit 

Could you execute the following code on your system?

```
wget https://raw.githubusercontent.com/logancloud/logan-app-operator/master/scripts/webhook-create-signed-cert.sh

sh webhook-create-signed-cert.sh --service webhook-test --namespace chaos-testing --secret webhook-test

kubectl get secret webhook-test -n chaos-testing -o yaml

```

The code work like the `webhook-certs-job`.

**Comment by wwjgit** [comment] 2020-04-08 02:57
@Gallardot 
I got webhook-test created.

kubectl get secrets -n chaos-testing
NAME                                   TYPE                                  DATA   AGE
chaos-controller-manager-token-9jlwl   kubernetes.io/service-account-token   3      18h
chaos-dashboard-token-44wmg            kubernetes.io/service-account-token   3      17h
default-token-hhgrw                    kubernetes.io/service-account-token   3      2d1h
webhook-test                           Opaque                                2      38s

**Comment by Gallardot** [comment] 2020-04-08 03:40
```
apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-certs-job
  namespace: chaos-testing
  labels:
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/component: webhook-certs-job
    helm.sh/chart: chaos-mesh-dev
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: webhook-certs-job
    spec:
      restartPolicy: Never
      serviceAccountName: chaos-controller-manager
      containers:
        - name: "chaos-mesh-job-certs"
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - |
              set -e
              K8S_SERVICE=chaos-mesh-controller-manager
              K8S_SECRET=chaos-mesh-webhook-certs
              K8S_NAMESPACE=chaos-testing

              # test if secret already exists
              certs=$(kubectl get secret ${K8S_SECRET} --ignore-not-found -n ${K8S_NAMESPACE} -o name)

              if [ "${certs}" = "secret/${K8S_SECRET}" ];then
                echo "Secret already exists"
                exit 0
              fi

              csrName=${K8S_SERVICE}.${K8S_NAMESPACE}
              tmpdir=$(mktemp -d)
              echo "Creating certs in tmpdir ${tmpdir} "

              cat <<EOF >> ${tmpdir}/csr.conf
              [req]
              req_extensions = v3_req
              distinguished_name = req_distinguished_name
              [req_distinguished_name]
              [ v3_req ]
              basicConstraints = CA:FALSE
              keyUsage = nonRepudiation, digitalSignature, keyEncipherment
              extendedKeyUsage = serverAuth
              subjectAltName = @alt_names
              [alt_names]
              DNS.1 = ${K8S_SERVICE}
              DNS.2 = ${K8S_SERVICE}.${K8S_NAMESPACE}
              DNS.3 = ${K8S_SERVICE}.${K8S_NAMESPACE}.svc
              EOF

              openssl genrsa -out ${tmpdir}/server-key.pem 2048

              echo "generate csr"
              openssl req -new -key ${tmpdir}/server-key.pem -subj "/CN=${K8S_SERVICE}.${K8S_NAMESPACE}.svc" -out ${tmpdir}/server.csr -config ${tmpdir}/csr.conf

              # clean-up any previously created CSR for our service. Ignore errors if not present.
              kubectl delete csr ${csrName} 2>/dev/null || true

              echo "create CSR"
              # create server cert/key CSR and send to k8s API
              cat <<EOF | kubectl create -f -
              apiVersion: certificates.k8s.io/v1beta1
              kind: CertificateSigningRequest
              metadata:
                name: ${csrName}
              spec:
                groups:
                - system:authenticated
                request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
                usages:
                - digital signature
                - key encipherment
                - server auth
              EOF

              echo "verify CSR"
              # verify CSR has been created
              while true; do
                  kubectl get csr ${csrName}
                  if [ "$?" -eq 0 ]; then
                      break
                  fi
              done

              echo "approve certificats"
              # approve and fetch the signed certificate
              kubectl certificate approve ${csrName}

              # verify certificate has been signed
              for x in $(seq 10); do
                  serverCert=$(kubectl get csr ${csrName} -o jsonpath='{.status.certificate}')
                  if [ ! -z ${serverCert} ]; then
                      echo "not empty"
                      break
                  fi
                  sleep 1
              done

              if [ -z ${serverCert} ]; then
                  echo "ERROR: After approving csr ${csrName}, the signed certificate did not appear on the resource. Giving up after 10 attempts." >&2
                  exit 1
              fi

              echo "start to openssl base64"

              echo ${serverCert} | openssl base64 -d -A -out ${tmpdir}/server-cert.pem

              # create the secret with CA cert and server cert/key
              kubectl create secret generic ${K8S_SECRET} \
                      --from-file=tls.key=${tmpdir}/server-key.pem \
                      --from-file=tls.crt=${tmpdir}/server-cert.pem \
                      --dry-run -o yaml |
                  kubectl -n ${K8S_NAMESPACE} apply -f -
                  sleep 60
```


@wwjgit Could you please save the above code as a yaml file. for example `xxx.yaml`

and execute the following
```
kubectl create -f xxx.yaml
kubectl describe jobs.batch -n chaos-testing

# find a pod with `webhook` prefix.
 kubectl get pod -n chaos-testing -o wide

# get logs
kubectl logs  -f webhook-xxxxxxxxxx

```

Please forgive me and thank you for your understanding.

**Comment by wwjgit** [comment] 2020-04-08 14:02
@Gallardot It works. chaos-controller-manager is running. Many thanks.

**Comment by Gallardot** [comment] 2020-04-08 14:17
> @Gallardot It works. chaos-controller-manager is running. Many thanks.

@wwjgit 
It's very strange.I still don't know why `helm install` doesn't work.What version of helm are you using?

```
helm version
```


@shiju-tech 
As mentioned above, dose it work for your? Please let me know, Thank you.

**Comment by shiju-tech** [comment] 2020-04-08 17:45
@Gallardot 

**kubectl get secrets -n chaos-testing**

chaos-controller-manager-token-7tsh6   kubernetes.io/service-account-token   3      2d1h
default-token-97xpq                    kubernetes.io/service-account-token   3      2d1h
sh.helm.release.v1.chaos-mesh.v1       helm.sh/release.v1                    1      2d1h
webhook-test                           Opaque                                2      57s



**kubectl create -f webhook-certs-job.yaml**
job.batch/webhook-certs-job created

**kubectl describe jobs.batch -n chaos-testing**

Name:           webhook-certs-job
Namespace:      chaos-testing
Selector:       controller-uid=71ee59c1-eafb-4c93-b223-06fbdcbc2b26
Labels:         app.kubernetes.io/component=webhook-certs-job
                app.kubernetes.io/instance=chaos-mesh
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=chaos-mesh
                helm.sh/chart=chaos-mesh-dev
Annotations:    helm.sh/hook: pre-install
                helm.sh/hook-delete-policy: hook-succeeded
                helm.sh/hook-weight: -2
Parallelism:    1
Completions:    1
Start Time:     Wed, 08 Apr 2020 17:31:31 +0000
Pods Statuses:  1 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           controller-uid=71ee59c1-eafb-4c93-b223-06fbdcbc2b26
                    job-name=webhook-certs-job
  Service Account:  chaos-controller-manager
  Containers:
   chaos-mesh-job-certs:
    Image:      bitnami/kubectl:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      set -e
      K8S_SERVICE=chaos-mesh-controller-manager
      K8S_SECRET=chaos-mesh-webhook-certs
      K8S_NAMESPACE=chaos-testing

      # test if secret already exists
      certs=$(kubectl get secret ${K8S_SECRET} --ignore-not-found -n ${K8S_NAMESPACE} -o name)

      if [ "${certs}" = "secret/${K8S_SECRET}" ];then
        echo "Secret already exists"
        exit 0
      fi

      csrName=${K8S_SERVICE}.${K8S_NAMESPACE}
      tmpdir=$(mktemp -d)
      echo "Creating certs in tmpdir ${tmpdir} "

      cat <<EOF >> ${tmpdir}/csr.conf
      [req]
      req_extensions = v3_req
      distinguished_name = req_distinguished_name
      [req_distinguished_name]
      [ v3_req ]
      basicConstraints = CA:FALSE
      keyUsage = nonRepudiation, digitalSignature, keyEncipherment
      extendedKeyUsage = serverAuth
      subjectAltName = @alt_names
      [alt_names]
      DNS.1 = ${K8S_SERVICE}
      DNS.2 = ${K8S_SERVICE}.${K8S_NAMESPACE}
      DNS.3 = ${K8S_SERVICE}.${K8S_NAMESPACE}.svc
      EOF

      openssl genrsa -out ${tmpdir}/server-key.pem 2048

      echo "generate csr"
      openssl req -new -key ${tmpdir}/server-key.pem -subj "/CN=${K8S_SERVICE}.${K8S_NAMESPACE}.svc" -out ${tmpdir}/server.csr -config ${tmpdir}/csr.conf

      # clean-up any previously created CSR for our service. Ignore errors if not present.
      kubectl delete csr ${csrName} 2>/dev/null || true

      echo "create CSR"
      # create server cert/key CSR and send to k8s API
      cat <<EOF | kubectl create -f -
      apiVersion: certificates.k8s.io/v1beta1
      kind: CertificateSigningRequest
      metadata:
        name: ${csrName}
      spec:
        groups:
        - system:authenticated
        request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
        usages:
        - digital signature
        - key encipherment
        - server auth
      EOF

      echo "verify CSR"
      # verify CSR has been created
      while true; do
          kubectl get csr ${csrName}
          if [ "$?" -eq 0 ]; then
              break
          fi
      done

      echo "approve certificats"
      # approve and fetch the signed certificate
      kubectl certificate approve ${csrName}

      # verify certificate has been signed
      for x in $(seq 10); do
          serverCert=$(kubectl get csr ${csrName} -o jsonpath='{.status.certificate}')
          if [ ! -z ${serverCert} ]; then
              echo "not empty"
              break
          fi
          sleep 1
      done

      if [ -z ${serverCert} ]; then
          echo "ERROR: After approving csr ${csrName}, the signed certificate did not appear on the resource. Giving up after 10 attempts." >&2
          exit 1
      fi

      echo "start to openssl base64"

      echo ${serverCert} | openssl base64 -d -A -out ${tmpdir}/server-cert.pem

      # create the secret with CA cert and server cert/key
      kubectl create secret generic ${K8S_SECRET} \
              --from-file=tls.key=${tmpdir}/server-key.pem \
              --from-file=tls.crt=${tmpdir}/server-cert.pem \
              --dry-run -o yaml |
          kubectl -n ${K8S_NAMESPACE} apply -f -
          sleep 60

    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age    From            Message
  ----    ------            ----   ----            -------
  Normal  SuccessfulCreate  2m40s  job-controller  Created pod: webhook-certs-job-c2vx9


 **kubectl get pod -n chaos-testing -o wide**
webhook-certs-job-c2vx9                     0/1     ErrImagePull        0          3m13s

Failed to pull image "bitnami/kubectl:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.xxx.xxx.xxx:53: no such host

**Comment by wwjgit** [comment] 2020-04-09 01:49
helm version
Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}

**Comment by Gallardot** [comment] 2020-04-10 02:34
> Failed to pull image "bitnami/kubectl:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.xxx.xxx.xxx:53: no such host

@shiju-tech 
Can you make sure that each Kubernetes node has the access to docker.io?

**Comment by Gallardot** [comment] 2020-04-10 03:07
> helm version
> Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}

@wwjgit 
I install the v2.16.5 helm, but I can't reproduce the error.  😂

**Comment by wwjgit** [comment] 2020-04-10 09:22
@Gallardot chaos-mesh is running perfectly on my system. I will let you know if that happens again. Thanks a lot for the help.

**Comment by shiju-tech** [comment] 2020-04-14 12:50
@Gallardot  issue seems with my company proxy , will let you know , once it is fixed

**Comment by shiju-tech** [comment] 2020-04-14 13:59
@Gallardot  the issue is fixed , i gave access to every node by enabling the  proxies to  pull the image from docker.io  , thank you

**Comment by Gallardot** [comment] 2020-04-16 06:50
@wwjgit  @shiju-tech 

I'll close the issue. If you have any questions, please feel free to reopen it.

**Closed by Gallardot** 2020-04-16 06:50 UTC
