### ISSUE TITLE
Cannot uninstall iochaos when sidecar chaosfs running failed

### ISSUE THREAD

**Issue by mahjonp** [pingcap/chaos-mesh#126] opened 2020-01-12 02:50 UTC
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Follow the [doc](https://github.com/pingcap/chaos-mesh/diffs/4?base_sha=717b1b26775ca6eb2699db33cdcf874c28d6570e&commentable=true&head_user=cwen0&pull_number=121&sha1=717b1b26775ca6eb2699db33cdcf874c28d6570e&sha2=7ab71cc71eaeb045cfef603d9f5c5af9a588ddb4&short_path=0cea7a9&unchanged=expanded&utf8=%E2%9C%93#available-methods) to test iochaos #121 on TiKV.

I found the sidecar chaosfs was in the `Waiting` state because of CrashLoopBackOff, so I want to uninstall iochaos.

**What did you expect to see?**

uninstall iochaos successfully.

**What did you see instead?**

found the command is hanging:

```
$ kubectl delete -f examples/io-mixed-example.yaml
iochaos.pingcap.com "io-delay-example" deleted
...
```

here are part of controller logs:

```
2020-01-12T02:42:05.380Z	INFO	controllers.IoChaos	Recover I/O chaos action, network is not ok, retrying...	{"iochaos": "chaos-testing/io-delay-example", "reconciler": "chaosfs", "namespace": "default", "name": "demo-tikv-0"}
2020-01-12T02:42:07.380Z	INFO	controllers.IoChaos	Recover I/O chaos action, network is not ok, retrying...	{"iochaos": "chaos-testing/io-delay-example", "reconciler": "chaosfs", "namespace": "default", "name": "demo-tikv-0"}
2020-01-12T02:42:09.379Z	INFO	controllers.IoChaos	Recover I/O chaos action, network is not ok, retrying...	{"iochaos": "chaos-testing/io-delay-example", "reconciler": "chaosfs", "namespace": "default", "name": "demo-tikv-0"}
2020-01-12T02:42:11.380Z	INFO	controllers.IoChaos	Recover I/O chaos action, network is not ok, retrying...	{"iochaos": "chaos-testing/io-delay-example", "reconciler": "chaosfs", "namespace": "default", "name": "demo-tikv-0"}
2020-01-12T02:42:13.380Z	INFO	controllers.IoChaos	Recover I/O chaos action, network is not ok, retrying...	{"iochaos": "chaos-testing/io-delay-example", "reconciler": "chaosfs", "namespace": "default", "name": "demo-tikv-0"}
2020-01-12T02:42:15.379Z	ERROR	controllers.IoChaos	failed to recover I/O chaos action	{"iochaos": "chaos-testing/io-delay-example", "reconciler": "chaosfs", "namespace": "default", "name": "demo-tikv-0", "error": "timed out waiting for the condition"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/manjunpeng/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/pingcap/chaos-mesh/controllers/iochaos/fs.(*Reconciler).recoverPod
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/iochaos/fs/types.go:184
github.com/pingcap/chaos-mesh/controllers/iochaos/fs.(*Reconciler).cleanFinalizersAndRecover
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/iochaos/fs/types.go:152
github.com/pingcap/chaos-mesh/controllers/iochaos/fs.(*Reconciler).Recover
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/iochaos/fs/types.go:112
github.com/pingcap/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/twophase/types.go:87
github.com/pingcap/chaos-mesh/controllers/iochaos.(*Reconciler).Reconcile
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/iochaos/types.go:46
github.com/pingcap/chaos-mesh/controllers.(*IoChaosReconciler).Reconcile
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/iochaos_controller.go:43
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/Users/manjunpeng/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/manjunpeng/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/Users/manjunpeng/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/manjunpeng/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/manjunpeng/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/manjunpeng/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:88
2020-01-12T02:42:15.379Z	ERROR	controllers.IoChaos	failed to recover chaos	{"iochaos": "chaos-testing/io-delay-example", "reconciler": "chaosfs", "error": "timed out waiting for the condition"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/manjunpeng/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/pingcap/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/twophase/types.go:89
github.com/pingcap/chaos-mesh/controllers/iochaos.(*Reconciler).Reconcile
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/iochaos/types.go:46
github.com/pingcap/chaos-mesh/controllers.(*IoChaosReconciler).Reconcile
	/Users/manjunpeng/Workspaces/chaos-mesh/controllers/iochaos_controller.go:43
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/Users/manjunpeng/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/manjunpeng/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/Users/manjunpeng/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/manjunpeng/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/manjunpeng/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/manjunpeng/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:88
```

**Comment by mahjonp** [comment] 2020-01-12 02:55
I logged the chaosfs sidecar container, found this ERROR, PTAL @ethercflow :

```
$ kubectl logs -f demo-tikv-0 -c chaosfs 
Chaosfs Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"89189f934e4ff90f6a6ab2bfb80a1abd6f65a050", GitTreeState:"dirty", BuildDate:"2020-01-12T02:12:00Z", GoVersion:"go1.13.3", Compiler:"gc", Platform:"linux/amd64"}
2020-01-12T02:46:03.851Z	INFO	chaos-daemon	Init hookfs
2020-01-12T02:46:03.851Z	ERROR	chaos-daemon	failed to create pid file	{"error": "pid file found, ensure docker is not running or delete /tmp/fuse/pid"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/manjunpeng/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
	/Users/manjunpeng/Workspaces/chaos-mesh/cmd/chaosfs/main.go:105
runtime.main
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/proc.go:203
```

**Comment by cwen0** [comment] 2020-01-12 05:26
@mahjonp Can you give me the log of the first crash of chaosfs? 

```
kubectl logs -f demo-tikv-0 -c chaosfs  -p 
```

**Comment by mahjonp** [comment] 2020-01-12 06:44
> @mahjonp Can you give me the log of the first crash of chaosfs?
> 
> ```
> kubectl logs -f demo-tikv-0 -c chaosfs  -p 
> ```

Sorry, the cluster had been destroyed.

**Comment by cwen0** [comment] 2020-02-05 02:51
this issue is caused by the data directory of the application, detail refers [faqs](https://github.com/pingcap/chaos-mesh/blob/master/doc/faqs.md#q-chaosfs-sidecar-container-run-failed-and-log-shows-pid-file-found-ensure-docker-is-not-running-or-delete-tmpfusepid), the delete command is hanging, because the chaos action is failed and we we recorded the target pod to finalizers of this chaos object. we can remove the finalizers from the chaos object when to delete this chaos object. 

I will close this issue.

**Closed** 2020-02-05 02:51 UTC
Labels: type/bug
