### ISSUE TITLE
Controller is always restarted and has some errors

### ISSUE THREAD

**Issue by gaocegege** [pingcap/chaos-mesh#156] opened 2020-01-20 09:43 UTC
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.7-gke.2", GitCommit:"96c91b15a936b36701e8704844bc356862440a21", GitTreeState:"clean", BuildDate:"2019-12-13T12:37:28Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Install chaos-mesh and keep it running for several days.

**What did you expect to see?**

Running without crashes and errors.

**What did you see instead?**

The controller is restarted several times.

```
NAME                                        READY   STATUS    RESTARTS   AGE
chaos-collector-database-69f75c4fd6-k6ghw   1/1     Running   0          6d5h
chaos-controller-manager-8fb4bfc78-68sdb    1/1     Running   11         6d5h
chaos-daemon-dfg59                          1/1     Running   0          6d5h
chaos-daemon-gndkg                          1/1     Running   0          6d5h
chaos-daemon-mfhmp                          1/1     Running   0          6d5h
chaos-daemon-n6m7h                          1/1     Running   0          6d5h
chaos-daemon-r9jdw                          1/1     Running   0          6d5h
chaos-dashboard-6654866f7c-twdwg            1/1     Running   0          6d5h
```

```
2020-01-15T10:24:51.258Z	ERROR	inject-webhook	channel has closed, should restart watcher
github.com/go-logr/zapr.(*zapLogger).Error
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/pingcap/chaos-mesh/pkg/webhook/config/watcher.(*K8sConfigMapWatcher).Watch
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/src/github.com/pingcap/chaos-mesh/pkg/webhook/config/watcher/watcher.go:122
main.watchConfig.func1.1
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/src/github.com/pingcap/chaos-mesh/cmd/controller-manager/main.go:176
2020-01-15T10:24:51.258Z	ERROR	setup	watcher got error, try to restart watcher	{"error": "watcher channel has closed"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.watchConfig.func1.1
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/src/github.com/pingcap/chaos-mesh/cmd/controller-manager/main.go:180
2020-01-15T10:24:53.259Z	INFO	setup	Launching watcher for ConfigMaps
2020-01-15T10:24:53.259Z	INFO	inject-webhook	Watching for ConfigMaps for changes	{"namespace": "chaos-testing", "labels": {"app.kubernetes.io/component":"webhook"}}
2020-01-15T11:13:57.608Z	ERROR	inject-webhook	channel has closed, should restart watcher
```

**Comment by zhouqiang-cl** [comment] 2020-01-20 10:09
@gaocegege thank you for your report, we will take a look

**Comment by gaocegege** [comment] 2020-01-20 10:18
@zhouqiang-cl Thanks for your reply. I can help if you need more information. And I will try to dive deeper into the bug, too.

**Comment by cwen0** [comment] 2020-01-20 10:23
@gaocegege hi, channel may closed caused by HTTP timeout, should restart watcher detail at https://github.com/kubernetes/client-go/issues/334, the Error is normal log, can you give me some log 
```
kubectl logs --namespace=chaos-testing chaos-controller-manager-xxx -p --tail=100 
```

**Comment by cwen0** [comment] 2020-01-20 10:55
@gaocegege I got the same issue with you and this might be useful for you.

**Comment by gaocegege** [comment] 2020-01-21 01:40
@cwen0 Here is the log:

```
Controller manager Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"8a33e3f8fbcfb343331fc723ef33a91e7d5e6227", GitTreeState:"dirty", BuildDate:"2020-01-14T06:01:42Z", GoVersion:"go1.13", Compiler:"gc", Platform:"linux/amd64"}
2020-01-15T09:45:29.219Z	ERROR	controller-runtime.manager	Failed to get API Group-Resources	{"error": "Get https://10.79.240.1:443/api?timeout=32s: dial tcp 10.79.240.1:443: i/o timeout"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/manager.New
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/manager.go:238
main.main
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/src/github.com/pingcap/chaos-mesh/cmd/controller-manager/main.go:93
runtime.main
	/usr/local/go/src/runtime/proc.go:203
2020-01-15T09:45:29.219Z	ERROR	setup	unable to start manager	{"error": "Get https://10.79.240.1:443/api?timeout=32s: dial tcp 10.79.240.1:443: i/o timeout"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
	/home/jenkins/agent/workspace/build_chaos_mesh_master/go/src/github.com/pingcap/chaos-mesh/cmd/controller-manager/main.go:100
runtime.main
	/usr/local/go/src/runtime/proc.go:203

```

**Comment by cwen0** [comment] 2020-01-21 14:00
@gaocegege According to the logs, the reason for the restart is most likely caused by the inaccessibility of the apiserver.

**Comment by gaocegege** [comment] 2020-01-26 02:53
Seems like that but other controllers (I deployed about 10 third party CRD operators) are working well.

**Comment by zhouqiang-cl** [comment] 2020-01-29 04:15
@cwen0 PTAL again

**Comment by cwen0** [comment] 2020-02-02 04:10
We may need more retry operations

**Comment by zhouqiang-cl** [comment] 2020-02-02 10:13
@gaocegege can you help to add some retry 😄

**Comment by zhouqiang-cl** [comment] 2020-02-09 05:57
We will add metrics https://github.com/pingcap/chaos-mesh/pull/210  and no more retry due to https://github.com/pingcap/chaos-mesh/issues/207
So. I will close this issue. If there are still anything abnormal, please reopen this issue @gaocegege

Thank you very much

**Closed** 2020-02-09 05:58 UTC
Labels: type/bug

**Comment by gaocegege** [comment] 2020-02-09 06:25
@zhouqiang-cl Thanks. Sorry for the late reply. I was busy on some other work about https://github.com/kubeflow/katib, sorry that cannot help.
